import Link from 'next/link';
import { getSiteSettings, getSupabase } from '../lib/supabase';

const DEFAULT_PHONE='204-632-4296';
const DEFAULT_ADDRESS='1129 Fife Street, Winnipeg, MB R2X 2N1';
function phoneHref(phone){return `tel:+1${String(phone||DEFAULT_PHONE).replace(/\D/g,'').replace(/^1/,'')}`}

export function Logo(){return <Link className="logo" href="/" aria-label="Right Choice Auto Repair & Car Sales home"><img src="/right-choice-logo.png" alt="Right Choice Auto Repair & Car Sales"/></Link>}
export async function Header(){const s=await getSiteSettings();const phone=s.phone||DEFAULT_PHONE;return <header className="header"><Logo/><nav><Link href="/">Home</Link><Link href="/cars">Cars for Sale</Link><Link href="/repairs">Auto Repair</Link><Link href="/about">About Us</Link><Link href="/contact">Contact</Link></nav><a className="call" href={phoneHref(phone)} aria-label={`Call Right Choice Auto at ${phone}`}>☎ Call Now</a></header>}
function formatHours(value){
  if(!value)return [];
  const text=String(value).replace(/\r/g,' ').replace(/\n+/g,' ').trim();
  const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
  const pattern=new RegExp(`(${days.join('|')})\\s*:?\\s*`,'gi');
  const matches=[...text.matchAll(pattern)];
  if(!matches.length)return [{day:'Hours',time:text}];
  return matches.map((m,i)=>{
    const start=m.index+m[0].length;
    const end=i+1<matches.length?matches[i+1].index:text.length;
    return {day:m[1][0].toUpperCase()+m[1].slice(1).toLowerCase(),time:text.slice(start,end).trim().replace(/^[–—-]\s*/,'')};
  }).filter(x=>x.time);
}
function safeExternalUrl(value){if(!value)return null;try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
function SocialIcon({name}){const icons={facebook:<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3 0-5 2-5 5v3H6v4h3v8h4v-8h3.3l.7-4H13V9c0-.7.3-1 1-1Z"/></svg>,instagram:<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5Zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7Zm5 3a5 5 0 1 1 0 10 5 5 0 0 1 0-10Zm0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm5.5-3.2a1.2 1.2 0 1 1 0 2.4 1.2 1.2 0 0 1 0-2.4Z"/></svg>,tiktok:<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 3c.3 2.2 1.6 3.8 4 4.4v3.1a8 8 0 0 1-4-1.3v6.1a5.7 5.7 0 1 1-5.7-5.7c.4 0 .8 0 1.2.1v3.2a2.6 2.6 0 1 0 1.3 2.4V3H15Z"/></svg>};return icons[name]||null}
export async function Footer(){const s=await getSiteSettings();const phone=s.phone||DEFAULT_PHONE;const address=s.address||DEFAULT_ADDRESS;const hours=formatHours(s.hours);const supabase=getSupabase();let services=[];if(supabase){const{data}=await supabase.from('services').select('id,name').eq('published',true).order('sort_order').limit(6);services=data||[]}const socials=[['facebook','Facebook',safeExternalUrl(s.facebook_url)],['instagram','Instagram',safeExternalUrl(s.instagram_url)],['tiktok','TikTok',safeExternalUrl(s.tiktok_url)]].filter(x=>x[2]);return <footer className="siteFooter"><div className="footerMain"><section className="footerBrand"><Logo/><p>{s.about_short||'Proudly serving Winnipeg and surrounding areas with quality auto repair and carefully selected used vehicles.'}</p><div className="footerTrust"><span>◆ Quality Vehicles</span><span>◆ Expert Service</span><span>◆ Honest &amp; Reliable</span></div></section><section className="footerCol"><h3>Quick Links</h3><Link href="/">Home</Link><Link href="/cars">Cars for Sale</Link><Link href="/repairs">Auto Repair</Link><Link href="/about">About Us</Link><Link href="/contact">Contact Us</Link></section><section className="footerCol"><h3>Our Services</h3>{services.length?services.map(x=><Link key={x.id} href="/repairs">{x.name}</Link>):<><Link href="/repairs">Oil Changes</Link><Link href="/repairs">Brake Service</Link><Link href="/repairs">Engine Diagnostics</Link><Link href="/repairs">General Repairs</Link></>}</section><section className="footerContact"><h3>Contact Us</h3><p className="footerAddress"><span className="footerIcon">⌖</span><span>{address}</span></p><a className="footerCall" href={phoneHref(phone)} aria-label={`Call Right Choice Auto at ${phone}`}>☎ Call Now</a>{hours.length>0&&<div className="footerHours"><span className="footerIcon">◷</span><div className="hoursList">{hours.map(x=><div className="hoursRow" key={x.day}><span>{x.day}</span><strong>{x.time}</strong></div>)}</div></div>}{socials.length>0&&<div className="socialLinks" aria-label="Social media">{socials.map(([name,label,url])=><a key={name} href={url} target="_blank" rel="noopener noreferrer" aria-label={label} title={label}><SocialIcon name={name}/></a>)}</div>}</section></div><div className="footerBottom"><small>© {new Date().getFullYear()} Right Choice Auto Repair &amp; Car Sales. All rights reserved.</small></div></footer>}
export function Money({value}){if(value===null||value===undefined||value==='')return <>Call for price</>;return <>${Number(value).toLocaleString('en-CA',{maximumFractionDigits:0})}</>}
export function VehicleCard({car}){const image=[...(car.vehicle_images||[])].sort((a,b)=>a.sort_order-b.sort_order)[0]?.image_url;const pending=car.status==='pending';return <article className={`vehicleCard${pending?' isPending':''}`}><Link href={`/cars/${car.id}`} className="photo">{image?<img src={image} alt={`${car.year} ${car.make} ${car.model}`}/>:<span>PHOTO COMING SOON</span>}{pending&&<span className="pendingWatermark">PENDING</span>}</Link><div className="cardBody"><div className="price"><Money value={car.price}/></div><h3>{car.year} {car.make} {car.model}</h3><p>{car.trim || ''}{car.mileage ? ` • ${Number(car.mileage).toLocaleString()} km` : ''}</p>{pending&&<span className="statusBadge pending">Pending Sale</span>}<Link className="textLink" href={`/cars/${car.id}`}>View Details →</Link></div></article>}
