'use client';
import {useMemo,useState} from 'react';
import {VehicleCard} from './components';
export default function InventoryBrowser({vehicles}){
 const [advanced,setAdvanced]=useState(false);
 const [query,setQuery]=useState(''),[make,setMake]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('newest'),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[minYear,setMinYear]=useState(''),[maxYear,setMaxYear]=useState(''),[maxMileage,setMaxMileage]=useState(''),[transmission,setTransmission]=useState(''),[drivetrain,setDrivetrain]=useState('');
 const transmissions=[...new Set(vehicles.map(v=>v.transmission).filter(Boolean))].sort();
 const drivetrains=[...new Set(vehicles.map(v=>v.drivetrain).filter(Boolean))].sort();
 const makes=[...new Set(vehicles.map(v=>v.make).filter(Boolean))].sort();
 const items=useMemo(()=>vehicles.filter(v=>(!query||`${v.year} ${v.make||''} ${v.model||''} ${v.trim||''}`.toLowerCase().includes(query.toLowerCase()))&&(!make||v.make===make)&&(status==='all'||v.status===status)&&(!minPrice||(v.price!==null&&Number(v.price)>=Number(minPrice)))&&(!maxPrice||(v.price!==null&&Number(v.price)<=Number(maxPrice)))&&(!minYear||Number(v.year)>=Number(minYear))&&(!maxYear||Number(v.year)<=Number(maxYear))&&(!transmission||v.transmission===transmission)&&(!drivetrain||v.drivetrain===drivetrain)&&(!maxMileage||(v.mileage!==null&&Number(v.mileage)<=Number(maxMileage)))).sort((a,b)=>sort==='price-low'?(Number(a.price??Infinity)-Number(b.price??Infinity)):sort==='price-high'?(Number(b.price??-1)-Number(a.price??-1)):sort==='year'?(Number(b.year)-Number(a.year)):new Date(b.created_at||0)-new Date(a.created_at||0)),[vehicles,query,make,status,sort,minPrice,maxPrice,minYear,maxYear,maxMileage,transmission,drivetrain]);
 const reset=()=>{setQuery('');setMake('');setStatus('all');setMinPrice('');setMaxPrice('');setMinYear('');setMaxYear('');setMaxMileage('');setTransmission('');setDrivetrain('');setSort('newest')};
 return <section className="inventoryBrowser" aria-label="Browse available vehicles"><div className="inventoryFilters"><div className="inventoryBasic"><label>Search inventory<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Make, model or year"/></label><label>Make<select value={make} onChange={e=>setMake(e.target.value)}><option value="">All makes</option>{makes.map(x=><option key={x}>{x}</option>)}</select></label><label>Maximum price ($)<input type="number" min="0" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="Any price"/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest listings</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="year">Year: newest first</option></select></label></div><div className="inventoryFilterActions"><button type="button" className="filterClear" aria-expanded={advanced} aria-controls="advanced-inventory-filters" onClick={()=>setAdvanced(v=>!v)}>{advanced?'Hide advanced filters':'Advanced filters'} {advanced?'−':'+'}</button><button type="button" className="filterClear" onClick={reset}>Clear filters</button></div>{advanced&&<div id="advanced-inventory-filters" className="inventoryAdvanced"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All listed</option><option value="available">Available</option><option value="pending">Pending</option></select></label><label>Minimum price ($)<input type="number" min="0" value={minPrice} onChange={e=>setMinPrice(e.target.value)} placeholder="Any price"/></label><label>Minimum year<input type="number" min="1900" max="2100" value={minYear} onChange={e=>setMinYear(e.target.value)} placeholder="Any year"/></label><label>Maximum year<input type="number" min="1900" max="2100" value={maxYear} onChange={e=>setMaxYear(e.target.value)} placeholder="Any year"/></label><label>Transmission<select value={transmission} onChange={e=>setTransmission(e.target.value)}><option value="">All</option>{transmissions.map(x=><option key={x}>{x}</option>)}</select></label><label>Drivetrain<select value={drivetrain} onChange={e=>setDrivetrain(e.target.value)}><option value="">All</option>{drivetrains.map(x=><option key={x}>{x}</option>)}</select></label><label>Maximum mileage (km)<input type="number" min="0" value={maxMileage} onChange={e=>setMaxMileage(e.target.value)} placeholder="Any mileage"/></label></div>}</div><p className="resultCount" aria-live="polite">Showing {items.length} of {vehicles.length} vehicles</p>{items.length?<div className="cards">{items.map(v=><VehicleCard car={v} key={v.id}/>)}</div>:<div className="empty"><h2>No matching vehicles</h2><p>Try adjusting your filters, or call 204-632-4296 for availability.</p><button type="button" className="filterClear" onClick={reset}>Reset filters</button></div>}</section>;
}
