-- Right Choice Auto v8: privacy-conscious analytics
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('page_view','vehicle_view','call_click','facebook_click','instagram_click','tiktok_click')),
  page_path text not null default '/',
  vehicle_id uuid null references public.vehicles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.analytics_events enable row level security;

drop policy if exists "public insert anonymous analytics" on public.analytics_events;
create policy "public insert anonymous analytics"
on public.analytics_events for insert to anon, authenticated
with check (
  event_name in ('page_view','vehicle_view','call_click','facebook_click','instagram_click','tiktok_click')
  and length(page_path) <= 300
);

drop policy if exists "admins read analytics" on public.analytics_events;
create policy "admins read analytics"
on public.analytics_events for select to authenticated
using (public.is_admin());

create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_vehicle_id_idx on public.analytics_events(vehicle_id);
